version: 1.1.{build}
image: WMF 5
install:
- ps: >-
    cinst pester

    cinst psget
build_script:
- ps: >-
    $moduleFile = Resolve-Path '.\OctopusStepTemplateCi\OctopusStepTemplateCi.psd1'

    Set-Content -Path $moduleFile -Value (Get-Content -Path $moduleFile | % {
      if ($_.StartsWith('ModuleVersion')) { "ModuleVersion = '{0}'" -f $env:APPVEYOR_BUILD_VERSION }
      else { $_ }
    })


    nuget.exe pack OctopusStepTemplateCi.nuspec -version $env:APPVEYOR_BUILD_VERSION -NoPackageAnalysis

    $nupkg = "OctopusStepTemplateCi.{0}.nupkg" -f $env:APPVEYOR_BUILD_VERSION

    Push-AppveyorArtifact (Resolve-Path $nupkg) -FileName $nupkg
test_script:
- ps: >-
    $res = Invoke-Pester -Path ".\OctopusStepTemplateCi\Cmdlets" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru -CodeCoverage (Get-ChildItem -Path ".\OctopusStepTemplateCi\Cmdlets" -File -Recurse -Include "*.ps1" -Exclude "*.Tests.ps1" | % FullName)

    (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))

    if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}


    $nupkg = Resolve-Path (".\OctopusStepTemplateCi.{0}.nupkg" -f $env:APPVEYOR_BUILD_VERSION)

    Import-Module PsGet

    PsGet\Install-Module -ModuleName OctopusStepTemplateCi -ModulePath $nupkg -Type ZIP -DoNotImport


    # Try loading module to validate

    Import-Module .\OctopusStepTemplateCi -Force -Verbose
artifacts:
- path: OctopusStepTemplateCi.%APPVEYOR_BUILD_VERSION%.nupkg
deploy: off
on_failure:
- ps: >-
    Get-ChildItem | Out-Host

    $blockRdp = $true

    iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))